language: python
python:
#   - "3.5" - pypact no longer supports 3.5
  - "3.6"
  - "3.7"
  - "3.8-dev"
# command to install dependencies
install:
  - pip install -r requirements.dev.txt
before_script:
  - export PYPACT=$PWD
  - export PYTHONPATH=$PYTHONPATH:$PYPACT/pypact
script:
  - pip3 install -e $PYPACT
  - python $PYPACT/setup.py test
  - bash scripts/run_coverage
# problem with pylint script - just ignore for now
#  - python scripts/run_pylint.py -j4 --rcfile=.pylintrc --output-format=text --score-threshold=4 pypact &> pylint.txt
#  - score=$(sed -n 's/^Your code has been rated at \([-0-9.]*\)\/.*/\1/p' pylint.txt)
#  - echo "Pylint score:" $score
  - fispactconverter.py $PYPACT/reference/test31.out test31.json
# run examples (no plotting)
  - cd $PYPACT/examples
  - python simple/doserates.py > dose.json
  - python simple/rundatajson.py > rundata.json
  - python simple/outputjson.py > output.json
  - python simple/readfilesfile.py > filesfile.out
  - python printlib/printlib5.py > printlib5.json
  - python inputcreation/changefilesfile.py > filesfile2.out
  - python inputcreation/writefilesfile.py
  - python inputcreation/writefluxesfile.py
  - python inputcreation/writeinputfile.py
  - python csv/tocsv.py
  - cd $PYPACT
after_success:
  - codecov
