name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Congratulations for submitting your first issue on pypact. Thanks for contributing!'
        pr-message: 'Congratulations for submitting your first pull request on pypact. Thanks for contributing!'
